import { SlimeDefinition, SlimeElement } from '../types/game';

export const slimeDefinitions: Record<string, SlimeDefinition> = {
  proto_slime: {
    id: 'proto_slime',
    displayName: 'プロトスライム',
    baseStats: { hp: 50, atk: 10, def: 8, spd: 12 },
    element: SlimeElement.CYBER,
    evolutionPaths: ['cyber_slime', 'acid_slime'],
    fusionTraits: ['adaptable', 'resilient'],
    spriteColor: '#00f3ff',
  },
  cyber_slime: {
    id: 'cyber_slime',
    displayName: 'サイバースライム',
    baseStats: { hp: 70, atk: 15, def: 12, spd: 18 },
    element: SlimeElement.CYBER,
    evolutionPaths: ['neon_knight'],
    fusionTraits: ['tech_savvy', 'fast'],
    spriteColor: '#0088ff',
  },
  acid_slime: {
    id: 'acid_slime',
    displayName: 'アシッドスライム',
    baseStats: { hp: 60, atk: 18, def: 10, spd: 14 },
    element: SlimeElement.ACID,
    evolutionPaths: ['toxic_blob'],
    fusionTraits: ['corrosive', 'toxic'],
    spriteColor: '#00ff66',
  },
  volt_slime: {
    id: 'volt_slime',
    displayName: 'ボルトスライム',
    baseStats: { hp: 55, atk: 20, def: 8, spd: 22 },
    element: SlimeElement.VOLT,
    evolutionPaths: ['thunder_core'],
    fusionTraits: ['electric', 'volatile'],
    spriteColor: '#ffff00',
  },
  void_slime: {
    id: 'void_slime',
    displayName: 'ヴォイドスライム',
    baseStats: { hp: 80, atk: 12, def: 15, spd: 10 },
    element: SlimeElement.VOID,
    evolutionPaths: ['dark_matter'],
    fusionTraits: ['absorbent', 'mysterious'],
    spriteColor: '#aa00ff',
  },
  neon_knight: {
    id: 'neon_knight',
    displayName: 'ネオンナイト',
    baseStats: { hp: 100, atk: 25, def: 20, spd: 22 },
    element: SlimeElement.CYBER,
    evolutionPaths: [],
    fusionTraits: ['knightly', 'radiant'],
    spriteColor: '#00ffff',
  },
  toxic_blob: {
    id: 'toxic_blob',
    displayName: 'トキシックブロブ',
    baseStats: { hp: 90, atk: 30, def: 15, spd: 18 },
    element: SlimeElement.ACID,
    evolutionPaths: [],
    fusionTraits: ['melting', 'hazardous'],
    spriteColor: '#00aa44',
  },
  thunder_core: {
    id: 'thunder_core',
    displayName: 'サンダーコア',
    baseStats: { hp: 85, atk: 35, def: 12, spd: 28 },
    element: SlimeElement.VOLT,
    evolutionPaths: [],
    fusionTraits: ['storm_bringer', 'charged'],
    spriteColor: '#ffcc00',
  },
  dark_matter: {
    id: 'dark_matter',
    displayName: 'ダークマター',
    baseStats: { hp: 120, atk: 20, def: 25, spd: 15 },
    element: SlimeElement.VOID,
    evolutionPaths: [],
    fusionTraits: ['void_touched', 'immovable'],
    spriteColor: '#6600aa',
  },
};
